remote_theme: dieghernan/chulapa


repository: dieghernan/chulapa
url: https://dieghernan.github.io
baseurl: chulapa


title: Chulapa
subtitle: A full flexible Jekyll theme  
description: Template for creating free sites on Github Pages
og_image: "./assets/img/site/banner.png" 
timezone: "Europe/Madrid"
author:
  name: dieghernan
  avatar: ./assets/img/site/dieghernan-avatar.png
  location: Madrid, Spain
  links:                
    - url: https://github.com/dieghernan/
      icon: "fab fa-github"
    - url: https://dieghernan.github.io/
      icon: fas fa-blog
    - url: https://stackoverflow.com/users/7877917/dieghernan
      icon: "fab fa-stack-overflow"
gtag_id:  UA-139034853-5
search:
  provider: algolia
  algolia_logo: true
algolia:                                                                   
  application_id        : "KOIKA5PDQO"
  index_name            : "chulapa"
  search_only_api_key   : "7f1fe42bef3f03458cb3a911ebc7e0ac"
  files_to_exclude:         #Optional
    - _layouts/*.html
    - _includes/*.html
    - _pages/liquid*
  extensions_to_index:      #Optional
    - html
    - md
  searchableAttributes:     #Optional                                                    
    - title                                                                    
    - headings                                                                 
    - unordered(content)                                                       
    - unordered(subtitle)                                                      
    - unordered(categories)                                                    
    - unordered(collection)                                                    
    - unordered(tags) 
  customRanking:            #Optional
    - desc(include_on_search)
    - desc(title)
    - desc(content) 
    - desc(subtitle)    
comments:
  provider: disqus
  disqus_shortname: chulapa
google_cse_id: 002514516175957445995:tvgnhtemtbu

# B. Navigation
navbar:
  style :  fab
  brand:
    title :  Home
    img: "./assets/img/site/brand-clear.png"
  nav:
  - title: Blog
    url: /blog/
  - title: Docs
    child:
     - title: Installation
       url: /docs/01-install
     - title: Global Settings
       url: /docs/02-config
     - title: Theming your site
       url: /docs/03-theming
     - title: Layouts & Snippets
       url: /docs/04-layouts
     - title: Tips & Tricks
       url: /docs/05-tips-n-tricks
     - title: Markdown cheatsheet
       url: /docs/markdown-cheatsheet
     - title: Syntax highlighting
       url: /docs/syntax-highlighting
     - title: Variable dictionary
       url: /docs/variable-dictionary
  - title: Skins		
    url: /skins
  - title: Demos
    child:
     - title: Index
       url: /demo
     - title: Archive (all)
       url: /demo/archive
     - title: Tag Cloud (2 cols)
       url: /demo/tags
     - title: Category Cloud (single)
       url: /demo/category
     - title: Search Google CSE
       url: /demo/search_google
     - title: Search LUNR
       url: /demo/search_lunr
     - title: Classic Navbar
       url: /demo/classic-navbar
  - title: About
    child: 
      - title: License
        url: /license
      - title: Showcase
        url: /showcase
      - title: Contribute
        url: /contribute
      - title: Changelog
        url: /CHANGELOG
footer:
  links:
    - label: "RSS"
      icon: "fa fa-rss"
      url:  "./atom.xml"
    - label: "GitHub"
      icon: "fab fa-github"
      url: https://github.com/dieghernan/
    - label: "My blog"
      icon: "fas fa-blog"
      url: "https://dieghernan.github.io/"

# C. Theme Settings
chulapa-skin: 
  highlight   : "github"
  autothemer  :  true 
  vars        :    
    primary:   '#efebdd'
    secondary: "#dfd7ba"
    link-color: '#a19d8e'

# D. Jekyll Defaults and collections: see https://jekyllrb.com/
collections:
  demo:
    output: true
    permalink: /demo/:name
  docs:
    output: true
    permalink: /docs/:name
  skins:
    output: true
    permalink: /skins/:name
collections_dir     : collections
permalink           : /:year:month:day_:title/
paginate: 4
paginate_path: "/blog/page:num/"
paginator_maxnum: 3 
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
      header_type         : "base"
      include_on_search   : false
      cloudtag_url        : "/tags"
      cloudcategory_url   : "/categories"
  -
    scope:
      path: ""
      type: "docs"
    values:
      header_type       : "hero"
      include_on_search : true
      show_bottomnavs   : true
      show_comments     : true
  -
    scope:
      path: ""
      type: "posts"
    values:
      header_type       : "post"
      include_on_search : true
      include_on_feed   : true
      show_date         : true
      show_bottomnavs   : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_author       : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Blog
          url: /blog/
  -
    scope:
      path: ""
      type: "skins"
    values:
      header_type       : "splash"
      cloudtag_url      : "/demo/tags"
      include_on_search : true
      show_date         : true
      show_sociallinks  : true
      show_comments     : true
      show_tags         : true
      show_categories   : true
      show_bottomnavs   : true
      show_author       : true
      show_toc          : true
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Skins
          url: /skins
  -
    scope:
      path: ""
      type: "demo"
    values:
      layout            : "default"
      header_type       : "base"
      cloudtag_url      : "/demo/tags"
      include_on_search : true
      cloudcategory_url : "/demo/category"
      show_breadcrumb   : true
      breadcrumb_list   :
        - label: Demo
          url: /demo
  -
    scope:
      path: "assets/img/gallery"
    values:
      image_col         : gallery

# XX. Other settings - no need to modify
compress_html:
  clippings: all
  blanklines: true
plugins:
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-sitemap
exclude:
  - LICENSE
  - README.md
  - Gemfile
  - vendor
  - www_src
include:
 - _pages
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  footnote_backlink: '&uarr;'
  entity_output: as_char
  toc_levels: 2..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  sass_dir: _sass
  style: compressed
